#' Calculates a monthly package download threshold
#'
#' @description
#' Looks at the monthly downloads of packages that are assigned a Task View.
#' Then uses this data to select a  monthly package download threshold to decide which packages, that are not assigned a Task View, will be used in model training.
#'
#' @details
#' The `get_CRAN_logs()` function is run inside [Train_model()].
#'
#' `get_CRAN_logs()` carries out the following steps:
#'  * Firstly, creates list object that gives the monthly downloads for each package in a Task View for the past month using [cranlogs::cran_downloads()].
#'    Using this list, it Computes the 75th percentile of the monthly downloads
#'  * Next, a vector of packages that are not assigned a Task View and whose monthly downloads exceeds this threshold is created.
#'    These packages are those that will be a labelled as not belonging to a Task Viw in the training of the model.
#'
#' @inheritParams get_NLP
#'
#' @return Returns
#' \itemize{
#'   \item `no_tsk_pckgs_meet_threshold` - vector of packages that are not assigned a Task View and meet monthly download threshold.
#'   \item `response_matrix`, `features`, `final_package_names`, `tvdb` - are objects created by CTVsuggest:::get_create_features function, that need to be carried forward.
#' }
#'
#'

get_CRAN_logs = function(TEST = FALSE,
                         limiting_n_observations = 100,
                         get_input_stored = FALSE,
                         get_input_path = "tests/testthat/fixtures/get_create_features_output/get_create_features_output.rds",
                         save_output = FALSE,
                         save_path = "tests/testthat/fixtures/get_CRAN_logs_output",
                         file_name = "get_CRAN_logs_output.rds") {



  # Objects needed to run generated by previous script:
  # tvdb
  # pac_network_igraph

  # Objects Outputted:
  # no_tsk_pckgs_meet_threshold



#### ----------------------------------------------------------------------------------------------- ####
  # Getting data
  # For testing may want to use prestored input object
  if(get_input_stored){
    get_create_features_output = readRDS(get_input_path)
    input_CRAN_data = get_create_features_output$input_CRAN_data
    tvdb = input_CRAN_data$tvdb
    TEST = attributes(input_CRAN_data)$TEST
    limiting_n_observations = attributes(input_CRAN_data)$limiting_n_observations

  }else{

    # Get required objects from CTVsuggest:::get_create_features()
    get_create_features_output = CTVsuggestTrain:::get_create_features(TEST = TEST, limiting_n_observations = limiting_n_observations)
    input_CRAN_data = get_create_features_output$input_CRAN_data
    tvdb = input_CRAN_data$tvdb
  }


#### ----------------------------------------------------------------------------------------------- ####

#### ----------------------------------------------------------------------------------------------- ####

  task_views = RWsearch::tvdb_vec(input_CRAN_data$tvdb)
  date = lubridate::today()

#### ----------------------------------------------------------------------------------------------- ####

#### ----------------------------------------------------------------------------------------------- ####

  ## CRAN downloads for All task views ##

  mnth_dwnloads = vector(length = length(task_views), mode = "list")
  names(mnth_dwnloads) = task_views


  message("Computing monthly download threshold for packages")
  # creates list, element for each Task View that contains tibble with number of monthly downloads for each package in the corresponding Task View.
  for(i in RWsearch::tvdb_vec(input_CRAN_data$tvdb)){
    # i = "Cluster"
    # pkg = tvdb_vec()[i]
    total_dec_21 <- cranlogs::cran_downloads(from = date %m-% months(1), to = date, packages = RWsearch::tvdb_pkgs(char = i, tvdb = input_CRAN_data$tvdb))
    total_dec_21$package = factor(total_dec_21$package)


    mnth_dwnloads[[i]] = total_dec_21 %>%
      dplyr::group_by(package) %>%
      dplyr::summarise(sum = sum(count))

  }


# lapply(mnth_dwnloads, function(x){median(x$sum)})
# lapply(mnth_dwnloads, function(x){median(x$sum)})
# unique(as.data.frame(rbindlist(mnth_dwnloads)))




# Decided on using 75th Percentile as threshold
# summary(unique(as.data.frame(rbindlist(mnth_dwnloads)))$sum)
# quantile(unique(as.data.frame(rbindlist(mnth_dwnloads)))$sum, 0.75)
# quantile(log(unique(as.data.frame(rbindlist(mnth_dwnloads)))$sum), 0.75)

# Creating histogram of past month Task View package downloads with line showing decided threshold
# hist(log(unique(as.data.frame(rbindlist(mnth_dwnloads)))$sum), breaks = 50, main = "Past month downloads\nof Task View packages", xlab = "log of month downloads")
# abline(v = log(2500), lty = 2, col = "red", lwd = 3)

#### ----------------------------------------------------------------------------------------------- ####

#### ----------------------------------------------------------------------------------------------- ####

  ## Creating vector of packages that have no assigned Task View. ##

  # Packages that are assigned to a Task View
  task_view_packages = Reduce(c,RWsearch::tvdb_pkgs(char = RWsearch::tvdb_vec(input_CRAN_data$tvdb), tvdb = input_CRAN_data$tvdb))
  task_view_packages = unique(task_view_packages)
  # Vector of package names that do not have a Task View
  no_tsk_view_packages = get_create_features_output$final_package_names[!get_create_features_output$final_package_names %in% task_view_packages]
  no_tsk_view_packages = unique(no_tsk_view_packages)
  # Remove R package, as it cannot be queried with other packages with cran_downloads
  if(length(which(no_tsk_view_packages == "R") > 0)){
    no_tsk_view_packages = no_tsk_view_packages[-which(no_tsk_view_packages == "R")]
  }

#### ----------------------------------------------------------------------------------------------- ####

#### ----------------------------------------------------------------------------------------------- ####

  ## Finding monthly downloads of packages that have no assigned Task view. ##

  # Can not query downloads number of too many packages at the same time, so need to chunk
  # Can query 800 at a time, maybe more
  # past_mnth_CRAN_logs <- cran_downloads(from = date %m-% months(1), to = date, packages = no_tsk_view_packages[sample(1:15863, 800)])


  # splitting into chunks
  chunk_size = 500
  n_chunks = ceiling(length(no_tsk_view_packages)/chunk_size)
  no_tsk_downloads_ls = vector(mode = "list", length = n_chunks)

  message("Finding packages that are not assigned to a CRAN Task View and do not meet monthly download threshold")
  if(n_chunks == 1){
    i = 1
    j = 1:length(no_tsk_view_packages)

    no_tsk_downloads <- cranlogs::cran_downloads(from = date %m-% months(1), to = date, packages = no_tsk_view_packages[j])

    no_tsk_downloads_ls[[i]] = no_tsk_downloads %>%
      dplyr::group_by(package) %>%
      dplyr::summarise(sum = sum(count)) %>%
      dplyr::filter(sum > 2500)

  } else {

  # first (n_chunks - 1)
  for(i in 1:(n_chunks - 1)){

    j = (1 + (chunk_size*(i - 1))):(chunk_size + (chunk_size*(i - 1)))

    no_tsk_downloads <- cranlogs::cran_downloads(from = date %m-% months(1), to = date, packages = no_tsk_view_packages[j])

    no_tsk_downloads_ls[[i]] = no_tsk_downloads %>%
      dplyr::group_by(package) %>%
      dplyr::summarise(sum = sum(count)) %>%
      dplyr::filter(sum > 2500)
  }

  # final chunk
  j = (((n_chunks -1) * chunk_size) + 1):length(no_tsk_view_packages)
  no_tsk_downloads <- cranlogs::cran_downloads(from = date %m-% months(1), to = date, packages = no_tsk_view_packages[j])

  no_tsk_downloads_ls[[n_chunks]] = no_tsk_downloads %>%
    dplyr::group_by(package) %>%
    dplyr::summarise(sum = sum(count)) %>%
    dplyr::filter(sum > 2500)

  }

  # Number of not assigned packages that meet threshold
  #length(unique(rbindlist(no_tsk_downloads_ls)$package))

  # Checking if R meets threshold
  # cran_downloads(from = date %m-% months(1), to = date, packages = "R") %>%
  #   summarise(sum = sum(count)) %>%
  #   filter(sum > 2500)
  #
  # # It does, so add to list
  # nrow(rbindlist(no_tsk_downloads_ls)) + 1

  no_tsk_pckgs_meet_threshold = c(data.table::rbindlist(no_tsk_downloads_ls)$package, "R")

#### ----------------------------------------------------------------------------------------------- ####

  list_to_return = list("response_matrix" = get_create_features_output$response_matrix, "features" = get_create_features_output$features,
            "final_package_names" = get_create_features_output$final_package_names,
            "no_tsk_pckgs_meet_threshold" = no_tsk_pckgs_meet_threshold, "tvdb" = tvdb)



  CTVsuggestTrain:::save_or_return_objects(TEST = TEST, list_to_return = list_to_return, limiting_n_observations = limiting_n_observations,
                                         save_output = save_output, save_path = save_path, file_name = file_name)


}
