on:
  schedule:
    - cron: "40 11 * * TUE"

name: schedule-train-model

jobs:
  ctvsuggesttrain-train-model:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Run Train_model
        run: CTVsuggestTrain::Train_model(save_output = TRUE, save_path = "OUTPUT/")
        shell: Rscript {0}

      - name: Commit and Push model output
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
